# Generated by Django 3.2.5 on 2021-07-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210708_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='min_date',
            field=models.DateField(null=True),
        ),
    ]
