# Generated by Django 3.2.5 on 2021-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_campaign_min_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='min_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='columns',
            field=models.TextField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='satart_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
