# Generated by Django 3.2.5 on 2021-07-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_satart_date_campaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
