# Generated by Django 3.2.5 on 2021-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210710_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
