# Generated by Django 3.2.5 on 2021-07-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210710_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='var1',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='var2',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
