# Generated by Django 3.2.5 on 2021-07-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210710_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='columns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
